name: Workflow Scan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/*'
  push:
    paths:
      - '.github/workflows/*'

permissions: # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  contents: read

jobs:
  workflow-scans:
    name: Workflow Scans
    runs-on: ubuntu-latest

